### ISSUE TITLE
Implementation of OpenCR for custom robot platform

### ISSUE THREAD

**Issue by ycean** [ROBOTIS-GIT/OpenCR#284]
May I consult with you regarding the firmware, or require steps that I need to do in order to use OpenCR board for my custom robot platform. As previously I have been played with the turtlebot3, and get to know OpenCR board could provide the communication with rosserial among the remote pc and the robot. So I am interest to start a design of firmware configuration for my custom robot platform.

As I am actually unsure how is the schematic of robot control communication among the remote pc-sbc-openCR. I am unsure where to start with in order to prepare for my robot pin map assignment.

regards,
Yeoh

**Comment by ROBOTIS-Will** [comment]
Hi @ycean 

I'm sorry about the delayed response.

This GitHub issue thread is used only for reporting the issue related to the OpenCR.
We usually share what we know with the open source community instead of providing a thorough consultation.
Please use the [Community](https://community.robotis.us/) when looking for help in customizing a robot.
Our engineers and support team will be able to answer your inquiries through the community forum.

If you are using ROS2, below issue thread might help to understand how OpenCR communicates with the SBC(Raspberry Pi)
https://github.com/ROBOTIS-GIT/turtlebot3/issues/744
